name: "Run Static Analysis"

on: [push, pull_request]

jobs:

  pyright:
    name: "Type Check (Pyright)"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
      - name: "uv sync"
        run: uv sync --locked --all-extras --dev
      - name: "Activate uv virtualenv"
        run: |
          source .venv/bin/activate
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: "Run Pyright"
        uses: jakebailey/pyright-action@v3

  ruff:
    name: "Lint (Ruff)"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: "Run Ruff"
        uses: astral-sh/ruff-action@v3
